FROM node:lts-alpine AS build

ENV NPM_CONFIG_UPDATE_NOTIFIER=false
ENV NPM_CONFIG_FUND=false

WORKDIR /app

# Railway injects service variables at build time — Vite reads VITE_* during `npm run build`.
ARG VITE_APP_NAME
ARG VITE_ENABLE_ANALYTICS
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_GA_MEASUREMENT_ID
ARG VITE_HOTJAR_SITE_ID
ARG VITE_HOTJAR_VERSION
ARG VITE_CONTENTSQUARE_SCRIPT_URL

ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_ENABLE_ANALYTICS=$VITE_ENABLE_ANALYTICS
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_GA_MEASUREMENT_ID=$VITE_GA_MEASUREMENT_ID
ENV VITE_HOTJAR_SITE_ID=$VITE_HOTJAR_SITE_ID
ENV VITE_HOTJAR_VERSION=$VITE_HOTJAR_VERSION
ENV VITE_CONTENTSQUARE_SCRIPT_URL=$VITE_CONTENTSQUARE_SCRIPT_URL

COPY package*.json ./
RUN npm ci

COPY . ./
RUN npm run build

FROM caddy:2-alpine

WORKDIR /app

COPY Caddyfile ./
RUN caddy fmt Caddyfile --overwrite

COPY --from=build /app/dist ./dist

CMD ["caddy", "run", "--config", "Caddyfile", "--adapter", "caddyfile"]
